name = "bold-mouse-3bc3"
compatibility_date = "2024-01-01"
account_id = "62fb45b77a7da33a4614d06fab267b4b"
main = "_worker.js"

[assets]
directory = "."
binding = "ASSETS"

[vars]
ACCESS_TEAM_DOMAIN = "michka1620.cloudflareaccess.com"
ACCESS_AUD = "da266af71e91c84e1a206bb80d9dc343218b24fdb6485c4f9b3b5e970da6c5ab"
